import { formatRelativeTime, getFileTypeConfig } from './artifactDisplay'
import type { ChatDocumentArtifact } from './artifactTypes'

interface DocumentArtifactsProps {
  documents: ChatDocumentArtifact[]
}

export function DocumentArtifacts({ documents }: DocumentArtifactsProps) {
  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px' }}>
      {documents.map((doc, index) => {
        if (doc.status === 'failed') {
          const title =
            doc.action === 'created'
              ? 'Document creation failed'
              : doc.action === 'edited'
                ? 'Document edit failed'
                : 'Document replication failed'
          const progress =
            doc.expectedCount !== undefined
              ? `${doc.completedCount ?? 0} of ${doc.expectedCount} copies completed.`
              : null
          return (
            <div
              key={`failed-${doc.action}-${doc.filename}-${index}`}
              role="alert"
              style={{
                width: '280px',
                minWidth: '250px',
                padding: '16px',
                border: '1px solid #F2B8B5',
                borderRadius: '16px',
                backgroundColor: '#FEF3F2',
                color: '#912018',
              }}
            >
              <p style={{ margin: 0, fontSize: '14px', fontWeight: 590 }}>{title}</p>
              <p style={{ margin: '6px 0 0', fontSize: '13px', fontWeight: 510 }}>{doc.filename}</p>
              {progress && <p style={{ margin: '6px 0 0', fontSize: '12px' }}>{progress}</p>}
              <p style={{ margin: '6px 0 0', fontSize: '12px', lineHeight: '17px' }}>{doc.error}</p>
            </div>
          )
        }

        const fileConfig = getFileTypeConfig(doc.filename)
        const timeAgo = formatRelativeTime(doc.createdAt)
        return (
          <a
            key={doc.id}
            href={`/documents/${doc.id}`}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={`Open ${doc.filename} in a new tab`}
            style={{
              backgroundColor: '#FFFFFF',
              borderRadius: '25px',
              cursor: 'pointer',
              transition: 'box-shadow 0.15s ease',
              display: 'flex',
              flexDirection: 'column',
              width: '280px',
              minWidth: '250px',
              border: '1px solid #F0F0F0',
              color: 'inherit',
              textDecoration: 'none',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.08)'
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.boxShadow = 'none'
            }}
          >
            <div style={{ padding: 7 }}>
              <div
                style={{
                  backgroundColor: '#F1F2F4',
                  borderRadius: '17px',
                  padding: '25px 40px 0px 40px',
                  overflow: 'hidden',
                }}
              >
                <div
                  style={{
                    backgroundColor: '#FFFFFF',
                    padding: '9px 17px',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '7.66px',
                    height: '100px',
                  }}
                >
                  <p
                    style={{
                      margin: 0,
                      fontSize: '10px',
                      fontWeight: 590,
                      color: '#A8A8A8',
                      letterSpacing: '-0.5px',
                      lineHeight: '13.8px',
                    }}
                  >
                    {doc.filename.replace(/\.[^/.]+$/, '')}
                  </p>
                  <p
                    style={{
                      margin: 0,
                      fontSize: '6px',
                      fontWeight: 400,
                      color: '#454545',
                      letterSpacing: '-0.3px',
                      lineHeight: '8px',
                    }}
                  >
                    Document generated by Prism AI assistant
                  </p>
                  <p
                    style={{
                      margin: 0,
                      fontSize: '6px',
                      fontWeight: 400,
                      color: '#999999',
                      letterSpacing: '-0.3px',
                      lineHeight: '8px',
                    }}
                  >
                    Click to open and edit the document
                  </p>
                </div>
              </div>
            </div>

            <div style={{ paddingTop: '10px' }}>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  paddingLeft: '10px',
                }}
              >
                <div
                  style={{
                    width: '28px',
                    height: '28px',
                    borderRadius: '6px',
                    backgroundColor: fileConfig.bgColor,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                  }}
                >
                  {typeof fileConfig.icon === 'string' ? (
                    <span
                      style={{
                        fontSize: '9px',
                        fontWeight: 700,
                        color: fileConfig.color,
                        fontFamily: 'monospace',
                      }}
                    >
                      {fileConfig.icon}
                    </span>
                  ) : (
                    <div style={{ marginLeft: 10 }}>{fileConfig.icon}</div>
                  )}
                </div>
                <p
                  style={{
                    marginLeft: 15,
                    fontSize: '14px',
                    fontWeight: 510,
                    color: '#454545',
                    letterSpacing: '-0.7px',
                    lineHeight: '18px',
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    display: '-webkit-box',
                    WebkitLineClamp: 2,
                    WebkitBoxOrient: 'vertical',
                    flex: 1,
                  }}
                >
                  {doc.filename}
                </p>
              </div>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '7px',
                  flexWrap: 'wrap',
                  padding: '5px 20px 20px 20px',
                  paddingLeft: '10px',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span
                    style={{
                      fontSize: '12px',
                      fontWeight: 510,
                      color: '#888787',
                      letterSpacing: '-0.6px',
                      lineHeight: '16px',
                      whiteSpace: 'nowrap',
                    }}
                  >
                    Generated By Prism AI | {timeAgo}
                  </span>
                </div>

                <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center' }}>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                    <path
                      d="M11 7.5V11.5C11 11.7652 10.8946 12.0196 10.7071 12.2071C10.5196 12.3946 10.2652 12.5 10 12.5H2.5C2.23478 12.5 1.98043 12.3946 1.79289 12.2071C1.60536 12.0196 1.5 11.7652 1.5 11.5V4C1.5 3.73478 1.60536 3.48043 1.79289 3.29289C1.98043 3.10536 2.23478 3 2.5 3H6.5"
                      stroke="#9CA3AF"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                    <path
                      d="M9 1.5H12.5V5"
                      stroke="#9CA3AF"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                    <path
                      d="M5.5 8.5L12.5 1.5"
                      stroke="#9CA3AF"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </a>
        )
      })}
    </div>
  )
}
